### index
GET /api/rooms/1/comments HTTP/1.1
Host: localhost
Accept: application/json
Authorization: Bearer 1|nAQ4XBiBEsKYernl70G2ZH7UcdVeZhVlRgYzw2sK

### store
POST /api/rooms/4/comments
Host: localhost
Accept: application/json
content-type: application/json
Authorization: Bearer 1|nAQ4XBiBEsKYernl70G2ZH7UcdVeZhVlRgYzw2sK

{
    "body": "コメントしてます"
    
}

### destroy
DELETE /api/rooms/1/comments/1 HTTP/1.1
Host: localhost
Accept: application/json
Authorization: Bearer 1|nAQ4XBiBEsKYernl70G2ZH7UcdVeZhVlRgYzw2sK